Fix build `aiohttp-speedups`
Exception caused by abandoned cchardet library:

`src/cchardet/_cchardet.cpp:196:12: fatal error: longintrepr.h: No such file or directory`

See also:
* https://github.com/PyYoshi/cChardet/issues/81
* https://github.com/PyYoshi/cChardet/issues/81#issuecomment-1329126634